# stage 1: base(hanya install dependensi)
# base image yang kita pakai
FROM node:24-slim AS base
# tempate file fe kita disimpan di container
WORKDIR /app
#copy package.json dan package-lock.json ke container
COPY package*.json .
# install dependencies di kontainer
RUN npm install

# stage 2:development (hot-reload)
FROM base AS development

COPY . .

EXPOSE 5173

CMD [ "npm","run","dev","--","--host" ]

# stage 3: build
FROM base AS build
COPY . .
# menghasilkan folder dist / build hasil kompilasi
RUN npm run build

# stage 4: production (hanya menyajikan file statis, sangat ringan)
FROM nginx:alpine AS production
# salin hasil build stage3 ke folder public nginx
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD [ "nginx","-g","daemon off;" ]